import Link from "next/link";
import { renderContentBlock } from "../../../lib/renderContent";

const aboutData = {
  en: {
    title: "About Broast Sara: Fresh Halal Broast in Madinah",
    alt: "Broast Sara restaurant branch storefront with fresh halal broast signage in Madinah Al-Munawwarah.",
    description: "Learn about Broast Sara, one of Madinah Al-Munawwarah's most established broast chains, with 8 branches, daily halal slaughter, and HACCP-certified kitchens.",
    snippet: "Broast Sara is a Saudi-owned broast restaurant chain operating 8 branches — 7 in Madinah Al-Munawwarah and 1 in Yanbu — and is one of the most established broast chains in the city. Every chicken served is sourced from local Saudi farms, hand-slaughtered daily using the Islamic halal method with official halal conformity certificates from the Saudi Halal Center, and has never been frozen. Signature dishes include Original Broast, Spicy Haraq Broast, Sarookh Shawarma, and the in-house Legendary Garlic Thoum Sauce. All branches operate under HACCP food safety protocols with a published Food Safety Policy. Orders are available through HungerStation and WhatsApp, with the Abiar Al Mashi branch open 24 hours a day, seven days a week.",
    content: `

## Who Broast Sara Is

Broast Sara is a Saudi-owned broast restaurant chain based in Madinah Al-Munawwarah, operating 8 branches across two cities. Seven branches serve Madinah's residential and commercial districts — Al Aziziyyah, Ad Difa, Al Hijrah, Al Jumuah, Ar Rawabi, Az Zahrah, and Abiar Al Mashi — and one branch serves Yanbu on the Red Sea coast. Every branch serves the same menu, prepared to the same kitchen standard, from the same daily fresh halal chicken supply. Delivery is available through HungerStation and WhatsApp across all branches, with the Imam Bukhari branch reachable at 0533107787 and the Abiar Al Mashi branch reachable at 0530957742.

Broast Sara is not a franchise or a chain that built outward from a corporate template. It is a local Saudi business that grew branch by branch across Madinah's neighbourhoods, building its presence through consistent operational standards rather than advertising. The result is a network that covers most of Madinah's main residential zones, with customers who have been ordering from the same branch for years.

## What Broast Sara Stands For

Broast Sara was built on three operational commitments that are verifiable at any branch on any visit: fresh chicken that has never been frozen, daily halal slaughter using the Islamic method, and documented food safety under HACCP protocols. These are not brand values in the abstract. They are decisions that cost more and require more operational discipline than the alternatives, and they produce a measurably different result at the table.

The commitment to fresh-only chicken means Broast Sara sources locally from Saudi poultry suppliers and does not use imported frozen chicken at any branch. Daily halal slaughter means the chicken on a customer's tray was alive within 24 hours of the order, processed at a Saudi Halal Center certified facility. The published Food Safety Policy means the kitchen standards that produce the food are documented, not informal.

Broast Sara also became the first broast chain in the Abiar Al Mashi area to introduce 24-hour service, recognising that Madinah's late-night demand — from pilgrims returning from prayer, highway travellers, and shift workers — required a kitchen that stayed open rather than one that closed when volume dropped. That branch has operated around the clock since opening, including through Ramadan, public holidays, and Hajj season.

## How We Cook: The Broast Method

Broast is made in a sealed pressure fryer, not an open vat. That distinction produces a physically different result from standard fried chicken and explains why regular customers describe the crust and interior texture as a category apart from what other kitchens serve.

In an open fryer, moisture escapes from the chicken as steam throughout the cooking cycle. That escaping moisture softens the crust from inside and dries the meat as it cooks. In a pressure fryer, the cooking chamber seals shut. The steam generated by the chicken builds internal pressure rather than escaping. That pressurised environment raises the effective boiling point of water inside the meat, driving heat into the interior from both the oil and the steam side simultaneously. The crust sets harder and thinner under containment. The interior holds its juices because they were not driven out during cooking.

At Broast Sara, every chicken piece is marinated for a minimum of 12 hours before pressure frying. Marination on fresh chicken with intact cell walls works through osmosis — flavour compounds migrate inward through the cell membranes over time, distributing seasoning through the cross-section of the meat rather than concentrating it at the outer layer. Frozen chicken, where the freeze-thaw cycle has ruptured cell walls and depleted 3 to 8 percent of natural moisture, cannot absorb a marinade the same way. The [Broast vs Fried Chicken post](/en/blog/broast-vs-fried-chicken) covers the full technical comparison.

## Our Standards: Fresh Chicken, Daily Halal Slaughter, and Food Safety

Three specific standards govern how every piece of chicken on the Broast Sara menu is sourced, slaughtered, and prepared. Each is verifiable and documented.

### 100% Fresh Local Saudi Chicken, Never Frozen

Every chicken served at every Broast Sara branch is sourced from local Saudi farms and has never entered a freeze-thaw cycle at any point in the supply chain. The chicken is delivered fresh to each branch daily. There is no frozen backup stock. This is an operational choice that costs more and requires tighter logistics than sourcing frozen imported chicken, and it directly affects the result of the 12-hour marination and the pressure-frying process. The [Fresh vs Frozen Chicken post](/en/blog/fresh-vs-frozen-chicken-broast-sara-madinah) explains the cellular science behind why this difference matters.

### Daily Halal Slaughter Using the Islamic Method

Every chicken served at Broast Sara is hand-slaughtered daily using the Islamic halal method at a Saudi Halal Center certified facility. The method requires a Muslim slaughterer, the proper invocation before each cut, a single swift cut severing the trachea and both jugular veins, and complete blood drainage before processing. Official halal conformity certificates from the Saudi Halal Center accompany every delivery batch to every branch.

This is materially different from restaurants that serve imported frozen halal chicken from overseas facilities certified in their country of origin. Imported frozen halal may have been processed weeks or months before arriving in Saudi Arabia, through supply chains that cross multiple jurisdictions. Broast Sara's chicken is slaughtered locally, delivered fresh the same day, and certified per batch by the Saudi Halal Center. The [Is Broast Halal in Madinah post](/en/blog/is-broast-halal-madinah) documents the full halal compliance framework.

### HACCP Food Safety Protocols and Published Food Safety Policy

Broast Sara applies HACCP (Hazard Analysis and Critical Control Points) protocols across all 8 branches. HACCP is a preventive food safety framework that identifies and controls risks at every specific step in the food preparation process: raw chicken receiving and temperature verification, cold storage monitoring, marination temperature control, pressure frying to a minimum internal temperature of 74 degrees Celsius, and cross-contamination prevention between raw and cooked product.

Broast Sara's Food Safety Policy is published and publicly available on the [Food Safety Policy page](/en/legal/food-safety). The documentation is not a marketing claim — it is a formal record of the kitchen standards applied at every branch, available for any customer, inspector, or partner to review.

Local staff carry out these protocols at every branch. Broast Sara employs local Saudi and Madinah-based staff across its branch network, and food safety training is part of the operational standard applied at every location.

## Our Branches in Madinah and Yanbu

Broast Sara operates 7 branches across Madinah Al-Munawwarah and 1 branch in Yanbu. All 8 are verified on Google Maps with current addresses, operating hours, and direct navigation links.

Madinah branches by district:

- **Al Daheetha**: on Sakmah Ibn Abi Salamah Street, Al Aziziyyah district, reachable at 0596624929
- **Ad Difa (Imam Bukhari)**: the main branch, serving the northeastern residential belt
- **Al Hijrah**: on Prince Sultan Street, serving Al Hijrah and Ash Shaibiyah District
- **Al Jumuah (Hil Bahr)**: on Jaber Ibn Atik Street in the Al Jumuah district
- **Ar Rawabi (Aljwazat)**: near the Jawazat area in northern Madinah
- **Az Zahrah (Al Juruf)**: on Prince Naif Bin Abdulaziz Street in northern Madinah
- **Abiar Al Mashi**: open 24 hours a day, seven days a week, reachable at 0530957742

The Yanbu branch on Omar Bin Khattab Street in the Al Amarah district serves the full Broast Sara menu to the same fresh-chicken and HACCP standard as all Madinah locations.

The [Broast Sara Locations page](/en/locations) lists all branch addresses, phone numbers, and Google Maps links.

## What Makes Broast Sara Different

The broast market in Madinah includes a range of options, from international chains to local operations. What Broast Sara does differently is specific and verifiable, not a claim about taste or experience.

Most broast restaurants in Saudi Arabia source imported frozen chicken because it is cheaper, easier to stockpile, and more logistically straightforward than running a daily fresh-supply chain. Frozen chicken produces a different result in a pressure fryer: the freeze-thaw cycle ruptures cell walls, depletes natural moisture, and prevents the 12-hour marinade from penetrating into the meat at the same depth. Customers can observe the difference by breaking open a piece of correctly pressure-fried fresh chicken and checking whether the steam that releases carries the marinade scent from inside the meat, or only from the crust surface.

Broast Sara's halal standard is also more specific than "halal certified" language suggests. Daily local slaughter with per-batch Saudi Halal Center certificates is a different standard from imported frozen halal that may have been certified at the point of slaughter months earlier in another country.

The 24-hour operation at Abiar Al Mashi is also not standard across the Madinah broast market. It reflects an understanding of how Madinah operates — as a city whose food demand does not follow a standard restaurant window — and a commitment to maintaining the same fresh-chicken and HACCP standards at 3 AM as at 3 PM.

The [Best Broast in Madinah post](/en/blog/best-broast-in-madinah-broast-sara) explains these differentiators in further detail for anyone evaluating the Madinah broast market.

`,
    faqs: [
      { q: "What is Broast Sara?", a: "Broast Sara is a Saudi-owned broast restaurant chain based in Madinah Al-Munawwarah, operating 8 branches — 7 in Madinah and 1 in Yanbu. The chain serves pressure-fried broast made from 100% fresh local Saudi chicken hand-slaughtered daily using the Islamic halal method, with official halal conformity certificates from the Saudi Halal Center for every batch. Signature dishes include Original Broast, Spicy Haraq Broast, Sarookh Shawarma, and the in-house Legendary Garlic Thoum Sauce." },
      { q: "How many branches does Broast Sara have and where are they located?", a: "Broast Sara operates 8 branches in total: 7 in Madinah Al-Munawwarah covering the Ad Difa, Al Daheetha, Al Hijrah, Al Jumuah, Ar Rawabi, Az Zahrah, and Abiar Al Mashi districts, and 1 in Yanbu. All 8 branches have verified Google Maps listings. The main Imam Bukhari branch is reachable at 0533107787 and the Abiar Al Mashi branch, which is open 24 hours a day seven days a week, is reachable at 0530957742." },
      { q: "Is Broast Sara halal?", a: "Yes. Every chicken at Broast Sara is hand-slaughtered daily using the Islamic halal method — by a Muslim slaughterer with the proper invocation before each cut, complete blood drainage, and a Saudi Halal Center conformity certificate for every delivery batch. All chicken is locally sourced from Saudi farms and has never been frozen. This is documented in Broast Sara's published Food Safety Policy on the official website." },
      { q: "What makes Broast Sara different from other broast chains in Madinah?", a: "Broast Sara uses 100% fresh local Saudi chicken that has never been frozen — unlike most Madinah broast operations, which use cheaper imported frozen chicken. Fresh chicken absorbs the 12-hour marinade more deeply, retains more natural moisture during pressure frying, and produces a crunchier, juicier result. Broast Sara also publishes its Food Safety Policy with full HACCP documentation, and was the first broast chain to introduce 24-hour service in the Abiar Al Mashi area." },
      { q: "What is Broast Sara's signature dish?", a: "Broast Sara's signature dish is the Original Broast — fresh daily-slaughtered Saudi chicken marinated for 12 hours in a proprietary spice blend and pressure-fried in a sealed fryer to produce a crust that cracks audibly when broken and an interior that releases steam from within the meat. It is served with the Legendary Garlic Thoum Sauce, made in-house through garlic emulsification. The Spicy Haraq Broast and Sarookh Shawarma are the most ordered items alongside it." },
      { q: "Does Broast Sara use fresh or frozen chicken?", a: "Broast Sara uses 100% fresh local Saudi chicken at all 8 branches. The chicken is sourced daily from Saudi farms, hand-slaughtered each morning using the Islamic halal method, and cooked the same day. No frozen chicken is used at any branch at any time. This daily fresh supply chain is a core operational requirement that distinguishes Broast Sara's pressure-fried result from competitors using imported frozen chicken." },
      { q: "Does Broast Sara have food safety certifications?", a: "Yes. Broast Sara applies HACCP (Hazard Analysis and Critical Control Points) food safety protocols across all 8 branches, covering raw chicken temperature verification at receiving, cold storage monitoring, marination temperature control, pressure frying to a minimum internal temperature of 74 degrees Celsius, and cross-contamination prevention. The full Food Safety Policy is published publicly on the Broast Sara website. Every chicken batch also carries an official halal conformity certificate from the Saudi Halal Center." },
      { q: "How can I order from Broast Sara?", a: "Orders can be placed through the HungerStation app by searching for Broast Sara and selecting the nearest Madinah or Yanbu branch. Direct WhatsApp or phone orders are accepted at all branches. The main Imam Bukhari branch is reachable at 0533107787. For orders at any hour including late night and Ramadan suhoor, the Abiar Al Mashi branch operates 24 hours a day, seven days a week, reachable at 0530957742." }
    ]
  },
  ar: {
    title: "عن بروست سارة: بروست حلال طازج في المدينة المنورة",
    alt: "واجهة فرع مطعم Broast Sara مع لافتة البروست الحلال الطازج في المدينة المنورة.",
    description: "تعرف على Broast Sara، إحدى أعرق سلاسل البروست في المدينة المنورة، بـ8 فروع وذبح حلال يومي ومطابخ معتمدة بنظام HACCP.",
    snippet: "Broast Sara سلسلة مطاعم بروست سعودية الملكية تمتلك 8 فروع — 7 في المدينة المنورة و1 في ينبع — وهي من أعرق سلاسل البروست في المدينة. كل دجاجة تُقدَّم مصدرها مزارع سعودية محلية، وتُذبح يدويًا يوميًا بالطريقة الإسلامية الحلال مع شهادات مطابقة حلال رسمية من مركز الحلال السعودي، ولم تتعرض للتجميد قط. تشمل الأطباق المميزة Original Broast وSpicy Haraq Broast وSarookh Shawarma وLegendary Garlic Thoum Sauce المُحضَّرة داخل المطبخ. تعمل جميع الفروع وفق بروتوكولات HACCP لسلامة الغذاء مع سياسة سلامة غذاء منشورة. الطلبات متاحة عبر HungerStation وWhatsApp، مع فرع أبيار الماشي المفتوح 24 ساعة يوميًا، سبعة أيام في الأسبوع.",
    content: `

## من هي Broast Sara

Broast Sara سلسلة مطاعم بروست سعودية الملكية مقرها المدينة المنورة، تمتلك 8 فروع في مدينتين. سبعة فروع تخدم الأحياء السكنية والتجارية في المدينة المنورة — الدفاع، والدعيثة، والهجرة، والجمعة، والروابي، والزهراء، وأبيار الماشي — وفرع واحد يخدم ينبع على ساحل البحر الأحمر. تقدم كل فرع القائمة ذاتها، مُحضَّرة وفق المعيار المطبخي ذاته، من إمداد يومي متطابق من الدجاج الطازج الحلال. التوصيل متاح عبر HungerStation وWhatsApp في جميع الفروع، ويمكن التواصل مع فرع الإمام البخاري على 0533107787 وفرع أبيار الماشي على 0530957742.

Broast Sara ليست امتيازًا تجاريًا ولا سلسلة بُنيت انطلاقًا من قالب مؤسسي. إنها مشروع سعودي محلي نما فرعًا بعد فرع عبر أحياء المدينة المنورة، بنى حضوره من خلال معايير تشغيلية ثابتة لا من خلال الإعلانات. النتيجة شبكة تغطي معظم المناطق السكنية الرئيسية في المدينة المنورة، مع زبائن يطلبون من الفرع ذاته منذ سنوات.

## ما الذي تمثله Broast Sara

بُنيت Broast Sara على ثلاثة التزامات تشغيلية قابلة للتحقق في أي فرع وفي أي زيارة: دجاج طازج لم يتعرض للتجميد قط، وذبح حلال يومي بالطريقة الإسلامية، وسلامة غذاء موثقة وفق بروتوكولات HACCP. هذه ليست قيمًا للعلامة التجارية في المجرد. بل هي قرارات تكلف أكثر وتتطلب انضباطًا تشغيليًا أعلى من البدائل، وتُنتج نتيجة مختلفة قابلة للقياس على الطاولة.

الالتزام بالدجاج الطازج حصريًا يعني أن Broast Sara تُوَرِّد محليًا من موردي الدواجن السعوديين ولا تستخدم الدجاج المجمد المستورد في أي فرع. الذبح الحلال اليومي يعني أن الدجاج في طبق الزبون كان حيًا خلال 24 ساعة من الطلب، وتمت معالجته في منشأة معتمدة من مركز الحلال السعودي. سياسة سلامة الغذاء المنشورة تعني أن معايير المطبخ التي تُنتج الطعام موثقة لا غير رسمية.

كانت Broast Sara أيضًا أول سلسلة بروست في منطقة أبيار الماشي تُقدّم خدمة 24 ساعة، إدراكًا منها أن الطلب المتأخر في المدينة المنورة — من الحجاج العائدين من الصلاة، ومستخدمي الطريق السريع، وعمال الورديات — يحتاج مطبخًا يبقى مفتوحًا لا مطبخًا يُغلق حين ينخفض الحجم. هذا الفرع يعمل على مدار الساعة منذ افتتاحه، بما في ذلك خلال رمضان والأعياد الرسمية وموسم الحج.

## كيف نطبخ: طريقة البروست

يُصنع البروست في قلاية ضغط مغلقة، لا في وعاء مفتوح. هذا الفارق يُنتج نتيجة مختلفة فيزيائيًا عن الدجاج المقلي الاعتيادي، ويُفسّر لماذا يصف الزبائن المنتظمون القشرة والملمس الداخلي باعتبارهما فئة مستقلة عما تُقدّمه المطابخ الأخرى.

في القلاية المفتوحة، تتسرب الرطوبة من الدجاج كبخار طوال دورة الطهي. ذلك البخار المتسرب يُليّن القشرة من الداخل ويُجفّف اللحم أثناء الطهي. في قلاية الضغط، تُغلق غرفة الطهي بإحكام. يبني البخار المتولد من الدجاج ضغطًا داخليًا بدلًا من الهروب. تلك البيئة المضغوطة ترفع نقطة الغليان الفعلية للماء داخل اللحم، دافعةً الحرارة إلى الداخل من جهة الزيت ومن جهة البخار معًا في آنٍ واحد. تتصلب القشرة وتُصبح أرفع تحت الاحتواء. يحتفظ الداخل بعصاراته لأنها لم تُطرد أثناء الطهي.

في Broast Sara، تُتبَّل كل قطعة دجاج لمدة 12 ساعة على الأقل قبل القلي بالضغط. التتبيل على الدجاج الطازج ذي الجدران الخلوية السليمة يعمل عبر الأسموزية — تنتقل مركبات النكهة إلى الداخل عبر أغشية الخلايا بمرور الوقت، موزّعةً التتبيل عبر المقطع العرضي للحم بدلًا من تركيزه في الطبقة الخارجية. الدجاج المجمد، حيث أفسدت دورة التجميد والذوبان جدران الخلايا واستنزفت 3 إلى 8 بالمئة من الرطوبة الطبيعية، لا يمتص التتبيلة بالطريقة ذاتها. يتناول [منشور بروست مقابل الدجاج المقلي](/ar/blog/broast-vs-fried-chicken) المقارنة التقنية الكاملة.

## معاييرنا: الدجاج الطازج، والذبح الحلال اليومي، وسلامة الغذاء

ثلاثة معايير محددة تحكم كيفية توريد وذبح وتحضير كل قطعة دجاج في قائمة Broast Sara. كل منها قابل للتحقق وموثق.

### دجاج سعودي محلي طازج 100%، لم يتعرض للتجميد قط

كل دجاجة تُقدَّم في كل فرع من فروع Broast Sara مصدرها مزارع سعودية محلية ولم تدخل قط في دورة تجميد وذوبان في أي نقطة من سلسلة التوريد. يُسلَّم الدجاج طازجًا إلى كل فرع يوميًا. لا يوجد مخزون احتياطي مجمد. هذا خيار تشغيلي يكلف أكثر ويتطلب لوجستيات أكثر دقة من توريد الدجاج المجمد المستورد، ويؤثر مباشرة على نتيجة التتبيل لـ12 ساعة وعملية القلي بالضغط. يشرح [منشور الدجاج الطازج مقابل المجمد](/ar/blog/fresh-vs-frozen-chicken-broast-sara-madinah) العلم الخلوي وراء أهمية هذا الفارق.

### الذبح الحلال اليومي بالطريقة الإسلامية

كل دجاجة تُقدَّم في Broast Sara تُذبح يدويًا يوميًا بالطريقة الإسلامية الحلال في منشأة معتمدة من مركز الحلال السعودي. تتطلب الطريقة ذابحًا مسلمًا، وتلاوة التسمية الصحيحة قبل كل ذبح، وقطعة واحدة سريعة تقطع القصبة الهوائية والوريدَين الوداجيَّين، واستنزافًا كاملًا للدم قبل المعالجة. تُرافق شهادات مطابقة حلال رسمية من مركز الحلال السعودي كل دفعة توصيل إلى كل فرع.

هذا يختلف جوهريًا عن المطاعم التي تُقدّم دجاجًا حلالًا مجمدًا مستوردًا من منشآت خارجية معتمدة في بلد المنشأ. قد يكون الدجاج الحلال المجمد المستورد قد مرّت أسابيع أو أشهر على معالجته قبل وصوله إلى المملكة العربية السعودية، عبر سلاسل توريد تعبر ولايات قضائية متعددة. دجاج Broast Sara يُذبح محليًا، ويُسلَّم طازجًا في اليوم ذاته، ومعتمد بشهادة لكل دفعة من مركز الحلال السعودي. يُوثّق [منشور هل البروست حلال في المدينة المنورة](/ar/blog/is-broast-halal-madinah) إطار الامتثال الحلال الكامل.

### بروتوكولات HACCP لسلامة الغذاء وسياسة سلامة الغذاء المنشورة

تُطبّق Broast Sara بروتوكولات HACCP (تحليل المخاطر ونقاط التحكم الحرجة) في جميع الفروع الثمانية. HACCP إطار وقائي لسلامة الغذاء يُحدد ويتحكم في المخاطر في كل خطوة محددة من خطوات إعداد الطعام: استلام الدجاج الخام والتحقق من درجة الحرارة، ومراقبة التخزين البارد، والتحكم في درجة حرارة التتبيل، والقلي بالضغط إلى درجة حرارة داخلية لا تقل عن 74 درجة مئوية، ومنع التلوث المتقاطع بين المنتج الخام والمطهي.

سياسة سلامة الغذاء الخاصة بـBroast Sara منشورة ومتاحة للعموم على [صفحة سياسة سلامة الغذاء](/ar/legal/food-safety). التوثيق ليس ادعاءً تسويقيًا — بل هو سجل رسمي للمعايير المطبخية المُطبَّقة في كل فرع، متاح لأي زبون أو مفتش أو شريك للمراجعة.

يُنفّذ الموظفون المحليون هذه البروتوكولات في كل فرع. تُوظّف Broast Sara موظفين سعوديين ومقيمين في المدينة المنورة عبر شبكة فروعها، والتدريب على سلامة الغذاء جزء من المعيار التشغيلي المُطبَّق في كل موقع.

## فروعنا في المدينة المنورة وينبع

تمتلك Broast Sara 7 فروع في المدينة المنورة وفرعًا واحدًا في ينبع. جميع الفروع الثمانية موثقة على Google Maps مع العناوين الحالية وساعات العمل وروابط الملاحة المباشرة.

فروع المدينة المنورة بحسب الحي:

- **الدفاع (الإمام البخاري)**: الفرع الرئيسي، في شارع الإمام البخاري، يمكن التواصل معه على 0533107787
- **الدعيثة**: في شارع سكمة بن أبي سلمة، حي العزيزية، يمكن التواصل معه على 0596624929
- **الهجرة**: في شارع الأمير سلطان، يخدم حي الهجرة ومنطقة الشيبية
- **الجمعة (هل بحر)**: في شارع جابر بن عتيك في حي الجمعة
- **الروابي (الجوازات)**: بالقرب من منطقة الجوازات في شمال المدينة المنورة
- **الزهراء (الجرف)**: في شارع الأمير نايف بن عبدالعزيز في شمال المدينة المنورة
- **أبيار الماشي**: مفتوح 24 ساعة يوميًا، سبعة أيام في الأسبوع، يمكن التواصل معه على 0530957742

يخدم فرع ينبع في شارع عمر بن الخطاب في حي العمارة القائمةَ الكاملة لـBroast Sara بالمعيار ذاته للدجاج الطازج و HACCP المُطبَّق في جميع مواقع المدينة المنورة.

تُدرج [صفحة فروع Broast Sara](/ar/locations) جميع عناوين الفروع وأرقام الهواتف وروابط Google Maps.

## ما الذي يُميّز Broast Sara

يشمل سوق البروست في المدينة المنورة مجموعة من الخيارات، من السلاسل الدولية إلى العمليات المحلية. ما تفعله Broast Sara بشكل مختلف محدد وقابل للتحقق، لا ادعاء بالمذاق أو التجربة.

تُورّد معظم مطاعم البروست في المملكة العربية السعودية دجاجًا مجمدًا مستوردًا لأنه أرخص وأسهل في التخزين وأكثر يسرًا لوجستيًا من تشغيل سلسلة توريد يومية بالدجاج الطازج. يُنتج الدجاج المجمد نتيجة مختلفة في قلاية الضغط: تُمزق دورة التجميد والذوبان جدران الخلايا، وتستنزف الرطوبة الطبيعية، وتمنع التتبيلة لـ12 ساعة من التغلغل إلى اللحم بالعمق ذاته. يمكن للزبائن ملاحظة الفارق بفتح قطعة من الدجاج الطازج المقلي بالضغط بشكل صحيح والتحقق من أن البخار المنبعث يحمل عطر التتبيلة من داخل اللحم، لا من سطح القشرة فقط.

معيار الحلال في Broast Sara أيضًا أكثر تحديدًا مما توحي به عبارة "معتمد حلال". الذبح اليومي المحلي مع شهادات مركز الحلال السعودي لكل دفعة معيار مختلف عن الدجاج الحلال المجمد المستورد الذي ربما اعتُمد عند نقطة الذبح قبل أشهر في بلد آخر.

كذلك فإن التشغيل على مدار 24 ساعة في أبيار الماشي ليس معيارًا في سوق البروست بالمدينة المنورة. إنه يعكس فهمًا لكيفية عمل المدينة المنورة — كمدينة لا يتبع فيها الطلب على الطعام نافذة مطعم اعتيادية — والتزامًا بالحفاظ على معايير الدجاج الطازج وHACCP الساعة 3 فجرًا كما هي الساعة 3 ظهرًا.

يُفصّل [منشور أفضل بروست في المدينة المنورة](/ar/blog/best-broast-in-madinah-broast-sara) هذه المميزات بمزيد من التفصيل لمن يُقيّم سوق البروست في المدينة المنورة.

`,
    faqs: [
      { q: "ما هي Broast Sara؟", a: "Broast Sara سلسلة مطاعم بروست سعودية الملكية مقرها المدينة المنورة، تمتلك 8 فروع — 7 في المدينة المنورة و1 في ينبع. تُقدّم السلسلة بروستًا مقليًا بالضغط من دجاج سعودي محلي طازج 100% مذبوح يدويًا يوميًا بالطريقة الإسلامية الحلال، مع شهادات مطابقة حلال رسمية من مركز الحلال السعودي لكل دفعة. تشمل الأطباق المميزة Original Broast وSpicy Haraq Broast وSarookh Shawarma وLegendary Garlic Thoum Sauce المُحضَّرة داخل المطبخ." },
      { q: "كم عدد فروع Broast Sara وأين تقع؟", a: "تمتلك Broast Sara 8 فروع إجمالًا: 7 في المدينة المنورة تغطي أحياء الدفاع والدعيثة والهجرة والجمعة والروابي والزهراء وأبيار الماشي، و1 في ينبع. جميع الفروع الثمانية لديها قوائم موثقة على Google Maps. يمكن التواصل مع فرع الإمام البخاري الرئيسي على 0533107787، وفرع أبيار الماشي المفتوح 24 ساعة يوميًا، سبعة أيام في الأسبوع، على 0530957742." },
      { q: "هل Broast Sara حلال؟", a: "نعم. كل دجاجة في Broast Sara تُذبح يدويًا يوميًا بالطريقة الإسلامية الحلال — بواسطة ذابح مسلم مع التسمية الصحيحة قبل كل ذبح، واستنزاف كامل للدم، وشهادة مطابقة من مركز الحلال السعودي لكل دفعة توصيل. كل الدجاج مصدره محلي من مزارع سعودية ولم يتعرض للتجميد قط. هذا موثق في سياسة سلامة الغذاء المنشورة لـBroast Sara على الموقع الرسمي." },
      { q: "ما الذي يُميّز Broast Sara عن سلاسل البروست الأخرى في المدينة المنورة؟", a: "تستخدم Broast Sara دجاجًا سعوديًا محليًا طازجًا 100% لم يتعرض للتجميد قط — على خلاف معظم عمليات البروست في المدينة المنورة التي تستخدم دجاجًا مجمدًا مستوردًا أرخص ثمنًا. يمتص الدجاج الطازج تتبيلة الـ12 ساعة بعمق أكبر، ويحتفظ برطوبة طبيعية أكثر أثناء القلي بالضغط، وينتج نتيجة أكثر قرمشة وعصارة. كذلك تنشر Broast Sara سياسة سلامة الغذاء مع التوثيق الكامل لـHACCP، وكانت أول سلسلة بروست تُقدّم خدمة 24 ساعة في منطقة أبيار الماشي." },
      { q: "ما هو الطبق المميز لـBroast Sara؟", a: "الطبق المميز لـBroast Sara هو Original Broast — دجاج سعودي طازج مذبوح يوميًا، يُتبَّل لـ12 ساعة في خلطة بهارات خاصة ويُقلى في قلاية مغلقة بالضغط لإنتاج قشرة تُصدر صوتًا مسموعًا عند الكسر وداخل يُطلق البخار من عمق اللحم. يُقدَّم مع Legendary Garlic Thoum Sauce المُحضَّرة داخل المطبخ عبر استحلاب الثوم. Spicy Haraq Broast وSarookh Shawarma هما الصنفان الأكثر طلبًا إلى جانبه." },
      { q: "هل تستخدم Broast Sara دجاجًا طازجًا أم مجمدًا؟", a: "تستخدم Broast Sara دجاجًا سعوديًا محليًا طازجًا 100% في جميع الفروع الثمانية. يُوَرَّد الدجاج يوميًا من المزارع السعودية، ويُذبح كل صباح بالطريقة الإسلامية الحلال، ويُطهى في اليوم ذاته. لا يُستخدم أي دجاج مجمد في أي فرع في أي وقت. سلسلة التوريد اليومية بالدجاج الطازج هذه شرط تشغيلي أساسي يُميّز نتيجة القلي بالضغط في Broast Sara عن المنافسين الذين يستخدمون الدجاج المجمد المستورد." },
      { q: "هل لدى Broast Sara اعتمادات سلامة الغذاء؟", a: "نعم. تُطبّق Broast Sara بروتوكولات HACCP (تحليل المخاطر ونقاط التحكم الحرجة) في جميع الفروع الثمانية، وتشمل التحقق من درجة حرارة الدجاج الخام عند الاستلام، ومراقبة التخزين البارد، والتحكم في درجة حرارة التتبيل، والقلي بالضغط إلى درجة حرارة داخلية لا تقل عن 74 درجة مئوية، ومنع التلوث المتقاطع. سياسة سلامة الغذاء الكاملة منشورة علنًا على موقع Broast Sara. كما تحمل كل دفعة دجاج شهادة مطابقة حلال رسمية من مركز الحلال السعودي." },
      { q: "كيف يمكنني الطلب من Broast Sara؟", a: "يمكن تقديم الطلبات عبر تطبيق HungerStation بالبحث عن Broast Sara واختيار أقرب فرع في المدينة المنورة أو ينبع. الطلب المباشر عبر WhatsApp والهاتف مقبول في جميع الفروع. يمكن التواصل مع فرع الالدعيثة على 0596624929. للطلبات في أي ساعة بما في ذلك الليل المتأخر وسحور رمضان، يعمل فرع أبيار الماشي 24 ساعة يوميًا، سبعة أيام في الأسبوع، ويمكن التواصل معه على 0530957742." }
    ]
  }
};

export async function generateMetadata({ params }) {
  const resolvedParams = await params;
  const lang = resolvedParams.lang || "ar";
  const isEn = lang === "en";
  const d = aboutData[lang];
  const url = `https://broastsara.com/${lang}/about`;

  return {
    title: d.title,
    description: d.description,
    alternates: { canonical: url },
    openGraph: {
      title: d.title,
      description: d.description,
      url,
      images: ['/broast-sara-logo.webp'],
    }
  };
}

export default async function AboutPage({ params }) {
  const resolvedParams = await params;
  const lang = resolvedParams.lang || "ar";
  const isEn = lang === "en";
  const d = aboutData[lang];

  const jsonLd = {
    "@context": "https://schema.org",
    "@type": "AboutPage",
    "url": `https://broastsara.com/${lang}/about`,
    "name": d.title,
    "description": d.snippet,
    "mainEntity": {
      "@type": "Restaurant",
      "@id": "https://broastsara.com/#restaurant",
      "name": isEn ? "Broast Sara" : "بروست سارة",
      "description": d.snippet,
      "url": "https://broastsara.com",
      "telephone": "+966533107787",
      "priceRange": "SAR 5 - SAR 25",
      "servesCuisine": ["Middle Eastern", "Fried Chicken", "Fast Food", "Shawarma"],
      "address": {
        "@type": "PostalAddress",
        "streetAddress": isEn ? "Al Imam Al Bukhari Street" : "شارع الإمام البخاري",
        "addressLocality": isEn ? "Madinah Al-Munawwarah" : "المدينة المنورة",
        "postalCode": "42374",
        "addressCountry": "SA"
      },
      "areaServed": isEn ? "Madinah Al-Munawwarah, Saudi Arabia" : "المدينة المنورة، المملكة العربية السعودية",
      "numberOfLocations": 8,
      "aggregateRating": {
        "@type": "AggregateRating",
        "ratingValue": "4.1",
        "reviewCount": "1639"
      },
      "sameAs": [
        "https://maps.app.goo.gl/NaC1TNvGSqsYUtsT8"
      ]
    }
  };

  const faqJsonLd = {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    "mainEntity": d.faqs.map(faq => ({
      "@type": "Question",
      "name": faq.q,
      "acceptedAnswer": {
        "@type": "Answer",
        "text": faq.a
      }
    }))
  };

  return (
    <div className="w-full pt-40 pb-32 px-0 md:px-6 font-helvetica tracking-[-0.05em]" dir={isEn ? "ltr" : "rtl"}>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqJsonLd) }} />

      <div className="w-full max-w-4xl mx-auto liquid-glass overflow-hidden flex flex-col rounded-[40px] md:rounded-[40px]">
        <div className="animate-premium-in flex flex-col w-full text-start p-6 md:p-16">

          {/* Snippet / Quick Answer block */}
          <div className="mb-10 p-6 bg-white/5 border border-[#FFD700]/30 rounded-2xl italic text-white/90 text-lg md:text-xl leading-relaxed font-helvetica tracking-[-0.05em]">
            {d.snippet}
          </div>

          {/* Main content rendered via shared util */}
          <div className="w-full flex flex-col gap-6">
            {d.content.split('\n\n').map((block, index) => renderContentBlock(block, index))}
          </div>

          {/* CTA buttons */}
          <div className="mt-12 flex flex-col sm:flex-row gap-4 justify-center md:justify-start w-full border-t border-white/10 pt-10">
            <Link href={isEn ? "/en/order" : "/ar/order"} className="btn-primary w-full sm:w-auto flex items-center justify-center gap-3">
              <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M16 11V7a4 4 0 00-8 0v4M5 9h14l1 12H4L5 9z" /></svg>
              <span className="font-instrument tracking-normal text-xl">{isEn ? "Order Now" : "اطلب الآن"}</span>
            </Link>
            <Link href={isEn ? "/en/locations" : "/ar/locations"} className="btn-secondary w-full sm:w-auto flex items-center justify-center gap-3">
              <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M17.657 16.657L13.414 20.9a1.998 1.998 0 01-2.827 0l-4.242-4.243a8 8 0 1111.314 0z" /><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M15 11a3 3 0 11-6 0 3 3 0 016 0z" /></svg>
              <span className="font-instrument tracking-normal text-xl">{isEn ? "View Branches" : "عرض الفروع"}</span>
            </Link>
          </div>

          {/* FAQ section */}
          <section className="mt-16 pt-12 border-t border-white/20">
            <h2 className="text-3xl text-white mb-8 font-instrument tracking-normal text-start">
              {isEn ? "Frequently Asked Questions" : "الأسئلة الشائعة"}
            </h2>
            <div className="flex flex-col gap-6">
              {d.faqs.map((faq, i) => (
                <div key={i} className="bg-white/5 p-6 rounded-2xl border border-white/10 text-start">
                  <h3 className="text-xl text-white mb-3 font-instrument tracking-normal">{faq.q}</h3>
                  <p className="text-lg text-white leading-relaxed font-helvetica tracking-[-0.05em]">{faq.a}</p>
                </div>
              ))}
            </div>
          </section>

        </div>

        <div className="mb-12 text-center w-full">
          <Link href={isEn ? "/en" : "/"} className="text-[#FFD700] text-xl transition-colors font-instrument tracking-normal">
            {isEn ? "← Back to Home" : "← العودة للرئيسية"}
          </Link>
        </div>
      </div>

      {/* Mobile floating buttons */}
      <div className="fixed bottom-6 left-0 w-full z-[100] px-4 flex gap-3 md:hidden pointer-events-none" dir={isEn ? "ltr" : "rtl"}>
        <Link href={isEn ? "/en/order" : "/ar/order"} className="flex-1 bg-[#E31837] text-white py-4 rounded-full flex items-center justify-center gap-2 font-instrument text-lg shadow-[0_4px_20px_rgba(227,24,55,0.5)] pointer-events-auto no-underline">
          <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M16 11V7a4 4 0 00-8 0v4M5 9h14l1 12H4L5 9z" /></svg>
          {isEn ? "Order Now" : "اطلب الآن"}
        </Link>
        <Link href={isEn ? "/en/locations" : "/ar/locations"} className="flex-1 bg-black/40 border border-white/20 text-white py-4 rounded-full flex items-center justify-center gap-2 font-instrument text-lg backdrop-blur-md shadow-[0_4px_20px_rgba(0,0,0,0.4)] pointer-events-auto no-underline">
          <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M17.657 16.657L13.414 20.9a1.998 1.998 0 01-2.827 0l-4.242-4.243a8 8 0 1111.314 0z" /><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M15 11a3 3 0 11-6 0 3 3 0 116 0z" /></svg>
          {isEn ? "Branches" : "الفروع"}
        </Link>
      </div>
    </div>
  );
}